apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-data
  namespace: mail
  labels:
    app: stalwart
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
